//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaretdb.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnÇokZiyaretEdilenUrun
    {
        public int UrunID { get; set; }
        public string UrunAdı { get; set; }
        public string SeoPath { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public string ResimYolu { get; set; }
    }
}
