//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaretdb.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Müşteri> Müşteri { get; set; }
        public virtual DbSet<MüşteriTipi> MüşteriTipi { get; set; }
        public virtual DbSet<SepetItems> SepetItems { get; set; }
        public virtual DbSet<Slayt> Slayt { get; set; }
        public virtual DbSet<SlaytItems> SlaytItems { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ToplamUrunSayısı> ToplamUrunSayısı { get; set; }
        public virtual DbSet<UrunGörüntüleme> UrunGörüntüleme { get; set; }
        public virtual DbSet<UrunZiyaretcileri> UrunZiyaretcileri { get; set; }
        public virtual DbSet<WebSiteBlog> WebSiteBlog { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<EnÇokSatanUrunler> EnÇokSatanUrunler { get; set; }
        public virtual DbSet<EnÇokZiyaretEdilenUrun> EnÇokZiyaretEdilenUrun { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunResim> UrunResim { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
    }
}
