//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaretdb.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slayt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slayt()
        {
            this.SlaytItems = new HashSet<SlaytItems>();
        }
    
        public int SlaytID { get; set; }
        public string SlaytAdı { get; set; }
        public Nullable<System.DateTime> SlaytOlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> BaşlamaTarih { get; set; }
        public Nullable<System.DateTime> BitişTarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlaytItems> SlaytItems { get; set; }
    }
}
