//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaretdb.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlaytItems
    {
        public int SlaytItemsID { get; set; }
        public Nullable<int> SlaytID { get; set; }
        public string SlaytResim { get; set; }
        public string SipResim { get; set; }
        public string Slogan { get; set; }
        public string AltSlogan { get; set; }
        public string UrunURL { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Slayt Slayt { get; set; }
    }
}
