//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaretdb.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunZiyaretcileri
    {
        public int UrunZiyaretciID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> MüsteriID { get; set; }
        public Nullable<System.DateTime> ZiyaretTarihi { get; set; }
        public string ÖnerilenUrunUrl { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
