//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaretdb.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.SepetItems = new HashSet<SepetItems>();
            this.ToplamUrunSayısı = new HashSet<ToplamUrunSayısı>();
            this.UrunGörüntüleme = new HashSet<UrunGörüntüleme>();
            this.UrunResim = new HashSet<UrunResim>();
            this.UrunZiyaretcileri = new HashSet<UrunZiyaretcileri>();
        }
    
        public int UrunID { get; set; }
        public string UrunAdı { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> Stok { get; set; }
        public string Açıklama { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public Nullable<System.DateTime> EklenmeTARİHİ { get; set; }
        public string SeoPath { get; set; }
    
        public virtual EnÇokSatanUrunler EnÇokSatanUrunler { get; set; }
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetItems> SepetItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToplamUrunSayısı> ToplamUrunSayısı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunGörüntüleme> UrunGörüntüleme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunResim> UrunResim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunZiyaretcileri> UrunZiyaretcileri { get; set; }
    }
}
